### PR TITLE
Update REVIEWERS

### PR DESCRIPTION
**Pull request by olorin**
Anyone else want to be here? Happy to walk through the crypto stuff if
anyone's interested. /cc @NaevaTheCat @tranma

! @erikd-ambiata @thumphries
/jury approved @erikd-ambiata @thumphries

### CODE REVIEW

**Comment by erikd-ambiata** [comment]
:+1:

**Comment by thumphries** [comment]
👍  I'm about to go on extended leave so no point adding me (although as always I enjoy rubber ducking this stuff)

**Comment by NaevaTheCat** [comment]
I'd be keep to be a reviewer, could always stand to go more crazy

**Comment by olorin** [comment]
@NaevaTheCat I will walk through how our request-signing stuff works (codebase structure, protocols et cetera) sometime this week to bring her across the project conceptually. Anyone else interested in a walkthrough?

**Pull request merged**
